---
- hosts: all
  become: true
  become_user: root
  gather_facts: yes
  roles:
    - role: htop
      when: "ansible_facts['os_family'] == 'Debian'"
    - role: glances
      when: "ansible_facts['os_family'] == 'Debian'"