- hosts: webservers
  become: true
  become_user: root
  roles:
     - { role: notpixxl.ansible-ocsinventory-agent, ocsinventory_launch_options: "--server=http://myocsserver.domain.com/ocsinventory" }
