---
- hosts: all
  become: true
  become_user: root
  gather_facts: yes

  roles:
    - role: addadminusers
    - role: htop
      when: "ansible_facts['os_family'] == 'Debian'"
    - role: glances
      when: "ansible_facts['os_family'] == 'Debian'"
    - role: snmpd
      when: "ansible_facts['os_family'] == 'Debian'"
    - role: fail2ban
      when: "ansible_facts['os_family'] == 'Debian'"
  

  tasks:

    #Modify group_vars/idea_dependencies.yml to add packages to the provisionning 

    - name: Include vars of idea_dependencies.yml into the 'idea_dependencies' variable
      include_vars:
        file: group_vars/idea_dependencies.yml

    #This section install IDEA Provisionning dependancies that don't required custom config

    - name: install "{{ idea_dependencies }}" on Debian Linux OS Family
      apt:
        name: "{{ idea_dependencies }}"
        state: "{{ apt_install_state | default('latest') }}"
        update_cache: true
        cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
      when: "ansible_facts['os_family'] == 'Debian'"

    - name: install "{{ idea_dependencies }}" on RedHatLinux OS Family
      yum:
        name: "{{ idea_dependencies }}"
        state: "latest"
        update_cache: yes
      when: "ansible_facts['os_family'] == 'RedHat'"      