---
- hosts: all
  become: true
  become_user: root
  gather_facts: yes
  
  tasks:

    - name: Include vars of staff.yml into the 'users' variable
      include_vars:
        file: group_vars/staff.yml
        

    - name: Upgrade packages
      apt: upgrade=safe

    - name: Create users accounts
      user:
        name: "{{ item }}"
        state: present
        createhome: yes
        append: yes
        shell: /bin/bash
        # this is just a default password,it's SHA512 for "changeme"
        password: $6$lTAu5CUHVq$LPv0QEZukItGS9rNYVDj8IKlfcP2UoiYMymTBWyOTjJsrhXnSXnyyRouxB/9U703W0U3y2fdExNY4XBZnnwp8.
        update_password: on_create
      with_items: "{{ users }}"

    - name: Create sudoer's filename
      copy:
        dest: /etc/sudoers.d/{{ item }}
        content: "{{ item }} ALL=(ALL)  NOPASSWD: ALL"
      with_items: "{{ users }}"

    - name: Add .ssh directories
      file:
        path: /home/"{{ item }}"/.ssh
        state: directory
        mode: 0700
      with_items: "{{ users }}"

    - name: Add authorized keys
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"

    - name: Disallow root SSH access
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify: restart ssh

    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
      notify: restart ssh

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted