---
# tasks file for enable_apache2_statusmod
# enable status module, which is identified as status_module inside apache2
- apache2_module:
    state: present
    name: status
    identifier: status_module

- name: Comment local line in status.conf
    replace:
      path: /etc/apache2/mods-available/status.conf
      regexp: 'Require local'
      replace: '#Require local'

- name: Ensure Monitoring Server add access to status page
  lineinfile:
    path: /etc/apache2/mods-available/status.conf
    regexp: '^#Require ip '
    insertafter: '^#Require ip '
    line: Require ip 10.99.99.240/32
  notify: restart apache2
