---
# tasks file for ns_add_service
# Monitor monitor-1 must have been already setup

- name: Setup http service
  netscaler_service:
    nsip: '{{ nsip }}'
    nitro_user: '{{ nitro_user }}'
    nitro_pass: '{{ nitro_password }}'

    state: present
    name: '{{ inventory_hostname }}_http'
    servername: '{{ inventory_hostname }}'
    servicetype: HTTP
    port: 80
    cip: enabled
    cipheader: X-Forwarded_For
    comment: '{{ ns_conf.webserver_hostname }}_http_service'
    save_config: no

    monitor_bindings:
      - monitorname: http
        weight: 1

  delegate_to: localhost
  notify: Save configuration