---
# handlers file for ns_add_server
- name: Save configuration
  delegate_to: localhost
  netscaler_save_config:
    nsip: '{{ nsip }}'
    nitro_user: '{{ nitro_user }}'
    nitro_pass: '{{ nitro_password }}'