- name: my_playbook
  hosts: all
  become: yes
  tasks:

  - name: création d'un fichier
    file: 
      path: /tmp/pixxl.txt
      state: touch
      owner: cpiveteau

  - name: test de stat
    stat:
      path: /tmp/pixxl.txt
    register: __stat_pixxl

  - name: affichage stat
    debug:
      msg: "Mon Fichier existe ? {{ __stat_pixxl.stat.exists }}"

  - name: creation du repertoire pixxl
    file:
      path: /tmp/pixxl
      state: directory    
    when: __stat_pixxl.stat.exists == true