---
# tasks file for arillso.sudoers

- name: add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: install
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ sudoers_dependencies }}"

- name: update specific configuration files
  become: true
  template:
    src: etc/sudoers.d/sudoers.j2
    dest: "/etc/sudoers.d/{{ item.key }}"
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: 0440
  with_dict: "{{ sudoers_sudoers_d_files }}"
  tags:
    - configuration

- name: update global configuration file
  become: true
  template:
    src: etc/sudoers.j2
    dest: /etc/sudoers
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: 0440
  tags:
    - configuration
